version: '3'

services:
  backend-service:
    build: ./server
    expose: 
      - 8080
    volumes:
      - ./server:/srv/app/server
    ports:
      - 8080:8080
    command: npm run dev
  frontend-service:
    build: ./frontend-web
    volumes:
      - ./frontend-web/src:/srv/app/client/src
      - ./frontend-web/public:/srv/app/client/public
    expose:
      - 3000
    ports:
      - 3000:3000
    links:
      - backend-service
    command: npm run start