version: '3'

services:
  db-service:
    build: ./db
    # environment:
      # - MONGO_INITDB_DATABASE=omdb
      # - MONGO_INITDB_ROOT_USERNAME=omdb
      # - MONGO_INITDB_ROOT_PASSWORD=abcdefg
    volumes:
      # - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'
    networks:
      - mongo-backend
  backend-service:
    build: ./server
    env_file:
      - .env
    depends_on:
      - "db-service"
    expose: 
      - 5000
    volumes:
      - ./server:/srv/app/server
      - /srv/app/server/node_modules
    ports:
      - 5000:5000
    networks:
      - frontend-backend
      - mongo-backend
    command: npm run dev
  frontend-service:
    build: ./frontend-web
    depends_on:
      - "backend-service"
    volumes:
      - ./frontend-web/src:/srv/app/client/src
      - ./frontend-web/public:/srv/app/client/public
      - /srv/app/client/node_modules
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - frontend-backend
    command: npm run start

networks:
  frontend-backend:
  mongo-backend: